### ISSUE TITLE
wont open

### ISSUE THREAD

**Issue by Clyv1** [PyPylia/ultrakill-save-editor#19] opened 2024-05-26 04:11 UTC
ive tried all the versions but it just opens and almost instantly closes, idk what to do

**Comment by Ultramatteo22** [comment] 2024-06-17 18:51
the same thing happens to me, I can't open it, it just immediately closes.
I been waiting for a fix, none of the versions let me open it.

**Comment by TheCourpseOfKingUltraKillModder** [comment] 2024-11-11 04:26
same

**Comment by PyPylia** [comment] 2024-12-03 21:53
This is likely a duplicate of #13 unless you are running this on an older version that is supported. If so, please re-open this issue.

**Closed as completed by PyPylia** 2024-12-03 21:53 UTC
