### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by TheGreenEmo** [PyPylia/ultrakill-save-editor#22] opened 2024-11-10 08:02 UTC
It keep crashing ;-;

**Comment by TheCourpseOfKingUltraKillModder** [comment] 2024-11-11 04:25
same

**Comment by TheGreenEmo** [comment] 2024-11-11 04:48
It crashes when u imput it in the app? Does it?

**Comment by PyPylia** [comment] 2024-12-03 21:50
This is likely a duplicate of #13 unless you are running this on an older version that is supported. If so, please re-open this issue.

**Closed as completed by PyPylia** 2024-12-03 21:50 UTC
